### ISSUE TITLE
Update docker image to build with alpine elixir

### ISSUE THREAD

**Issue by Dkendal** [battle-snake/battle_snake#18]
We can cut down on total build image size by using alpine elixir as a base image instead of the debian based image we currently use.

See https://cloud.google.com/community/tutorials/elixir-phoenix-on-kubernetes-google-container-engine for an example dockerfile.

**Comment by cbinners** [comment]
See https://github.com/battle-snake/battle_snake/pull/21

**Comment by Dkendal** [comment]
implemented
